### ISSUE TITLE
conventional commits

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#16]
enforce conventional commits

[https://www.conventionalcommits.org/en/v1.0.0/(opens new window)](https://www.conventionalcommits.org/en/v1.0.0/)
[https://developer.vonage.com/en/blog/3-reasons-why-you-should-use-conventional-commits(opens new window)](https://developer.vonage.com/en/blog/3-reasons-why-you-should-use-conventional-commits)
[https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index(opens new window)](https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index)
https://github.com/semantic-release/semantic-release
https://github.com/go-semantic-release/semantic-release

**Comment by drewfugate** [comment]
Conventional commits should now be enforced via "gitlint" implemented for ticket #6 in pull request https://github.com/rise8-us/neverl8/pull/17 This was added as part of the pre commit hooks.

**Comment by jwills-r8** [comment]
found and interesting alternative to written in go for semantic-release https://github.com/go-semantic-release/semantic-release

**Comment by drewfugate** [comment]
Update: ticket is still in progress as I am looking into utilizing go-semantic-release as it is natively "GO", versus implementing via semantic-release in node.js.

**Comment by drewfugate** [comment]
go-semantic-release has been implemented and seems to be functioning properly.

![Image](https://github.com/rise8-us/neverl8/assets/102103212/2d1b80e8-9dbe-46f2-bc4e-b32059f1e902)
