### ISSUE TITLE
Get Access to Google services

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#18]
neverl8-api needs access to google workspace in order to pull user information, schedule meetings, and see calendars

cc: @WaylandP @jmiller-rise8 should be able to assist with this.

**Comment by jmiller-rise8** [comment]
@jwills-r8 I have the service account that can do this. I'll find the info tomorrow and give it to drew.

**Comment by jmiller-rise8** [comment]
I have given @drew-fugate-rise8 the creds
