### ISSUE TITLE
SPIKE: Select DB

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#2]
Pick Ideal DB solution.  Postgresql is current front runner.  Explore if there is a better option for the use case, i.e., NoSQL MongoDB or other.

**Comment by jwills-r8** [comment]
Step 1: Define Your Options
List all the options or solutions that have emerged from the spike. These could be different technologies, architectures, libraries, or approaches you're considering.

Options	Description
Option 1	Detailed description of Option 1
Option 2	Detailed description of Option 2
Option 3	Detailed description of Option 3
...	...
Step 2: Identify Criteria
Define the criteria you will use to evaluate each option. Criteria could include factors like cost, time to implement, compatibility with existing systems, performance, scalability, etc.

Criteria	Weight	Description
Cost	High	Total cost of implementation and maintenance
Time	Medium	Time required for implementation
Compatibility	High	How well it integrates with existing systems
Performance	Medium	Expected performance improvements or impacts
Scalability	Low	Ability to scale the solution in the future
...	...	...
Note: Weights are subjective and should reflect the priorities of your project or organization (e.g., High, Medium, Low).

Step 3: Rate Each Option Against Criteria
Rate how well each option meets the criteria on a scale (e.g., 1 to 5, where 5 is the best).

Options	Cost (High)	Time (Medium)	Compatibility (High)	Performance (Medium)	Scalability (Low)	Total
Option 1	4	3	5	4	2	
Option 2	2	4	3	5	4	
Option 3	3	5	4	3	5	
...	...	...	...	...	...	...
Step 4: Calculate Total Scores
Multiply each rating by the weight of its criterion (assuming High=3, Medium=2, Low=1 for simplicity) and sum them up for each option to get a total score. The option with the highest total score could be considered the preferred solution based on the criteria and weights you've defined.

Step 5: Make a Decision
Review the total scores along with any qualitative factors not captured by the matrix. Discuss the results with stakeholders and make a decision on which option to proceed with.

This decision matrix helps in making a structured and rational decision post-spike, taking into account various important factors and how each option measures up against them. It's a quantitative way to support what might otherwise be a qualitative or gut-feeling decision.

**Comment by drewfugate** [comment]
Removed cost as they are all free for commercial use, and should all be similar to maintain. Added team knowledge criteria, as it can speed up the time to deploy. There are plenty of other options to rank, but these 3 seem to be among the most widely used ones. My vote is for Postgres as well.

<google-sheets-html-origin>
  | Postgres | MySQL | Redis
-- | -- | -- | --
Description | Relational, reliable, and has advanced features. | Quick, easy to use relational | In-memory data structure, high speed and versatility.
Time | Moderate | Moderate | Minimal
Compatibility | Very high | High | Low
Performance | High | High | Very high
Scalability | Very high | High | Moderate
Team knowledge | High | Moderate | Low
Score Totals: | 16 | 13 | 11
