### ISSUE TITLE
DB Migration Management

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#20]
As a Developer
I want versioned Idempotent database migrations
So that I can easily understand db history, and update and rollback easily

Migrate docs:
https://pkg.go.dev/github.com/golang-migrate/migrate/v4
https://github.com/golang-migrate/migrate

Alternate Solutions:
https://github.com/pressly/goose

**Comment by drewfugate** [comment]
Migrations have been added in accordance with the DB diagram here https://dbdiagram.io/d/65e0e8eecd45b569fb3e5fa9
These changes can be found on #17 

Completion TODO: integrate Docker, as well as modify the CRUD functions in the program to properly integrate with the new db structure.
