### ISSUE TITLE
Configure Linter/Style checker

### ISSUE THREAD

**Issue by jwills-r8** [rise8-us/neverl8#6]
As a developer
I want the code to be consistent and clean
So that I can spend less time thinking about format and more time about logic.

### Acceptance criteria

- [ ]  Lint/checkstyle tool to define and enforce code
- [ ]  IntelliJ import order config file, to make imports from all contributers align.  (not sure if this applies)
- [ ] pre-commit hook to run all tests and run lint before commit

**Comment by drewfugate** [comment]
Moved to ready for review as this has been implemented in PR #17 

golangci is utilized for the linter, and the pre-commit hooks are specified in .pre-commit-config.yaml.
